### ISSUE TITLE
Can't build hello world example using solido repo as external repo

### ISSUE THREAD

**Issue by kkonevets** [ChorusOne/solido#557]
Can't build hello world example using solido repo as external repo https://github.com/kkonevets/solexamp
It uses latest solana-program-1.10.8  instead of solana-program-1.7.8 from your patch. Specifying dependencies does not help

![image](https://user-images.githubusercontent.com/16817116/162945220-0f41348d-7a59-4cc2-8d81-858235636e0d.png)

**Comment by ruuda** [comment]
As discussed elsewhere, adding this to your `Cargo.toml` will help:

```toml
[dependencies]
solana-sdk = "=1.7.8"
solana-program = "=1.7.8"
solana-program-test = "=1.7.8"
solana-frozen-abi = "=1.7.8"
solana-frozen-abi-macro = "=1.7.8"
```

The reason we still use `solana-sdk` 1.7.8 is because Anchor framework (the eDSL) has a dependency on `=1.7.8` (it doesn’t allow newer versions), and the multisig program uses Anchor framwork, and the CLI tool depends on that to build transactions ...
